### ISSUE TITLE
家庭安全版了？

### ISSUE THREAD

**Issue by ApolloRioo** [REIJI007/AdBlock_Rule_For_Clash#1]
xx都被禁了

**Comment by REIJI007** [comment]
啥意思？哪个被禁了？

**Comment by REIJI007** [comment]
全域名后缀误杀太严重了吧

**Comment by ApolloRioo** [comment]
> 啥意思？哪个被禁了？

估计你打包的是adguard家庭安全版，我在内容里搜到了这些域名，missav,supjav，有个正常的creat.missav是正常广告，在很后面，missav等主域名直接被禁了

**Comment by REIJI007** [comment]
上游列表封禁的，这里也会封禁，除非把它加入上游白名单，目前已查明||missav.com^来自上游列表https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt


已经有人反馈给上游了
https://github.com/jerryn70/GoodbyeAds/issues/498

**Comment by ApolloRioo** [comment]
就是家庭安全版，反馈没用的

**Comment by REIJI007** [comment]
我查了，封禁missav.com的不是adguard列表，就是来自GoodbyeAds的这个列表，哪里是什么安全版

**Comment by REIJI007** [comment]
要解决这个那你自行减少上游列表吧，fork了只添加自己信任的上游列表
