### ISSUE TITLE
误杀vscode的自动同步功能

### ISSUE THREAD

**Issue by liu-nian-dh** [REIJI007/AdBlock_Rule_For_Clash#2]
vscode日志
2024-10-28 16:35:04.593 [info] Request failed https://vscode-sync.trafficmanager.net/v1/manifest

clash日志
10-28 16:56:20 info [TCP] 127.0.0.1:50620 --> vscode-sync.trafficmanager.net:443 match RuleSet(adblock) using REJECT

Referencing rule sources.txt中包含trafficmanager.net的部分：
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt
@@||vscode-sync.trafficmanager.net^$stealth
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt
! Lead Forensics : ghochv3eng.trafficmanager.net disguised trackers
||o365diagtelemetry.trafficmanager.net^
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt
! Lead Forensics : ghochv3eng.trafficmanager.net disguised trackers
||o365diagtelemetry.trafficmanager.net^
||51tongji.trafficmanager.net^
||cnzz.trafficmanager.net^
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_224_Chinese/filter.txt
||51tongji.trafficmanager.net^
||cnzz.trafficmanager.net^
||trafficmanager.net^$domain=xpshuku.com
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_104_EasyListChina/filter.txt
||51tongji.trafficmanager.net^
||cnzz.trafficmanager.net^
||trafficmanager.net^$domain=xpshuku.com
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_118_EasyPrivacy/filter.txt
||trafficmanager.net/uet/tracking_script?
https://raw.githubusercontent.com/AdguardTeam/ADguardFilters/master/BaseFilter/sections/allowlist_stealth.txt
@@||vscode-sync.trafficmanager.net^$stealth
https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_original_trackers.txt
||ghochv3eng.trafficmanager.net^
https://raw.githubusercontent.com/AdguardTeam/ADguardFilters/master/SpywareFilter/sections/tracking_servers.txt
! Lead Forensics : ghochv3eng.trafficmanager.net disguised trackers
https://raw.githubusercontent.com/AdguardTeam/ADguardFilters/master/SpywareFilter/sections/tracking_servers_firstparty.txt
||o365diagtelemetry.trafficmanager.net^

**Comment by liu-nian-dh** [comment]
应该是这一条导致的
- '+.trafficmanager.net'

**Comment by REIJI007** [comment]
这是一个逻辑问题，```vscode-sync.trafficmanager.net```这个域名因为```@@||vscode-sync.trafficmanager.net^$stealth```这条规则被我排除在有效规则之外了，但是由于采用了clash的加号通配符，使得因为母域名```trafficmanager.net```被列入有效规则，最后造成依旧封禁```vscode-sync.trafficmanager.net```，现已调整clash规则集编写形式，去除加号通配符，采用封禁单个域名而不涉及递归所有子域名
